# Fly.io Configuration for Bento
# Documentation: https://fly.io/docs/reference/configuration/

app = "bento-fly"
primary_region = "iad"  # Washington, D.C. - change to your preferred region

# Build configuration
[build]
  dockerfile = "Dockerfile"

# Service configuration
[[services]]
  protocol = "tcp"
  internal_port = 8080  # Port Bento listens on
  auto_stop_machines = true   # Auto-stop when idle
  auto_start_machines = true  # Auto-start on request
  min_machines_running = 0    # Scale to zero when idle

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["http", "tls"]

  # Health checks
  [[services.http_checks]]
    interval = "15s"
    timeout = "10s"
    grace_period = "5s"
    method = "GET"
    path = "/ping"
    protocol = "http"

  # TCP health check
  [[services.tcp_checks]]
    interval = "15s"
    timeout = "10s"
    grace_period = "5s"

# VM Resources
[vm]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024  # 1 GB - comparable to Cloudflare's "basic" size

# Scaling
[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

# Metrics (optional)
[metrics]
  port = 9091  # If you add a Prometheus metrics server
  path = "/metrics"

# Environment variables (optional)
[env]
  # BENTO_ENV = "production"
  # LOG_LEVEL = "info"
